version: "3.8"

services:
  client:
    container_name: client
    image: node:14-alpine
    build:
      context: ./client
      target: client
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./client:/workspace
    command: /bin/sh -c "cd /workspace && yarn start"

  server:
    container_name: server
    image: node:14-alpine
    build:
      context: ./server
      target: server
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./server:/workspace
    command: /bin/sh -c "cd /workspace && yarn dev"
